### ISSUE TITLE
t/50glob.t fails

### ISSUE THREAD

**Issue by FGasper** [markov2/perl5-POSIX-1003#2]
```
#   Failed test 'error fn'
#   at t/50glob.t line 46.
#                   undef
#     doesn't match '(?^:^\/tmp\/s23DSaba/?$)'
Use of uninitialized value $got in numeric eq (==) at (eval in cmp_ok) t/50glob.t line 47.

#   Failed test 'error rc'
#   at t/50glob.t line 47.
Use of uninitialized value $val in addition (+) at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/Builder.pm line 796.
#          got: undef
#     expected: 13
# Looks like you failed 2 tests of 8.
t/50glob.t ........ 
```
This doesn’t appear to impede use of the module but does prevent installation without extra flags to skip tests.

Seen with:

- 5.32 on CentOS 7
- 5.24.1 on Raspbian 4.19.66-v7

**Comment by markov2** [comment]
When you are using a GitHUB version of the module, than you are not running a "released" version which means that I did not see my final tests.  However, for my final tests, I need testing on many platforms usually performed by cpantesters...

I really welcome your contributions: it makes me able to improve it faster.

**Comment by FGasper** [comment]
> On Nov 9, 2020, at 11:49 AM, Mark Overmeer <notifications@github.com> wrote:
> 
> 
> When you are using a GitHUB version of the module, than you are not running a "released" version which means that I did not see my final tests. However, for my final tests, I need testing on many platforms usually performed by cpantesters...
> 
> I really welcome your contributions: it makes me able to improve it faster.

I’m just trying to install the module via `cpan`.

This test also fails on macOS 10.14 w/ 5.26. (t/26time.t also fails on that platform.)

-F

**Comment by FGasper** [comment]
… which is to say, I’m not sure how it’s supposed to behave since it fails everywhere I’ve tried it.  Maybe that test should be commented out?

**Comment by markov2** [comment]
The compile issue you mentioned first is *not* in a released version of the module.  So, it seems you install from github, not from the cpan archives.  I do not know why.   Which version of the module does it try to install?

**Comment by FGasper** [comment]
It’s trying to install version 1.00.

**Comment by markov2** [comment]
The second warning you show in this bug-report originates from Test::Builder, not my test module.

Did you try to install POSIX-1003 the same way when you stumbled on the other bug, with #define in 1003.xs?  I can prove it was not in release 1.00 which I uploaded.

Looking at cpantesters (which had serious issues in the past months) I do not see your problem with glob (many other issues, but not this one)  See http://matrix.cpantesters.org/?dist=POSIX-1003+1.00   On the other hand: glob is a painful non-portable beast.  Do you, accidentally, not have a writable '/tmp'?  Can you make the test pass?

**Comment by FGasper** [comment]
The `#define` issue shouldn’t be relevant. All I’m doing is `cpan POSIX::1003::Fcntl`, which I think should just grab the version from CPAN.

I’ve not been able to make the test pass, no. `/tmp` is writable on all 3 systems where I see this failure.

**Comment by FGasper** [comment]
Do you have a raspberry pi w/ Raspbian? The stock `perl` on that system fails to install it for me.

**Comment by markov2** [comment]
I'll try to figure-out what's happening with your attempts after dinner (have to join my family now).  I cannot (yet) reproduce it on my Linux.

**Comment by FGasper** [comment]
Thank you! When I have a chance I’ll see about making it pass on this end, too.

**Comment by FGasper** [comment]
Curiously, while the 1.00 release fails, the newly-fixed git upstream passes. It looks like c2b2049e610a4e57f40e64df3bd6ddd8e4b035b7 is where it started working.

**Comment by markov2** [comment]
I made a mistake with tagging the POSIX::1003 on GitHUB, so when you get the zip of 1.00 it is not including patch c2b2049.  When you have my uploaded version to PAUSE (the usual source of the 'cpan' command) or the tar.gz version on GitHUB you get the correct one.

So, I really wonder which archive you are addressing and how that is being constructed.  I'll release 1.01 to fix the version confusion.

**Comment by FGasper** [comment]
Looking forward to 1.01, then. Thank you!
